name: Build and Deploy Pages Daily
on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: ${{ vars.REPOSITORY }}
          ref: ${{ vars.REF }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Build static site
        env:
          ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
          ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          CUSTOM_CONFIG: ${{ vars.CUSTOM_CONFIG }}
        run: |
          printf "%b\n" "$CUSTOM_CONFIG" > config/custom.yaml
          echo "Use custom config:"
          cat config/custom.yaml
          uv run src/zotero_arxiv_daily/main.py

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
